set(_AMENT_PACKAGE_NAME "ros2_livox_simulation")
set(ros2_livox_simulation_VERSION "0.0.0")
set(ros2_livox_simulation_MAINTAINER "rsc <stm32f303ret6@gmail.com>")
set(ros2_livox_simulation_BUILD_DEPENDS "rclcpp" "rclcpp_components" "gazebo_dev" "libprotobuf-dev" "gazebo_ros" "sensor_msgs" "tf2_ros" "geometry_msgs" "livox_ros_driver2")
set(ros2_livox_simulation_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(ros2_livox_simulation_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_components" "gazebo_dev" "libprotobuf-dev" "gazebo_ros" "sensor_msgs" "tf2_ros" "geometry_msgs" "livox_ros_driver2")
set(ros2_livox_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(ros2_livox_simulation_EXEC_DEPENDS "rclcpp" "rclcpp_components" "gazebo_dev" "libprotobuf-dev" "gazebo_ros" "sensor_msgs" "tf2_ros" "geometry_msgs" "livox_ros_driver2")
set(ros2_livox_simulation_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "ament_cmake_clang_format")
set(ros2_livox_simulation_GROUP_DEPENDS )
set(ros2_livox_simulation_MEMBER_OF_GROUPS )
set(ros2_livox_simulation_DEPRECATED "")
set(ros2_livox_simulation_EXPORT_TAGS)
list(APPEND ros2_livox_simulation_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND ros2_livox_simulation_EXPORT_TAGS "<gazebo_ros gazebo_plugin_path=\"../../lib\"/>")
