set(_AMENT_PACKAGE_NAME "robocon2027_gazebo")
set(robocon2027_gazebo_VERSION "0.1.0")
set(robocon2027_gazebo_MAINTAINER "ytr <ytr@todo.todo>")
set(robocon2027_gazebo_BUILD_DEPENDS "gazebo_dev" "gazebo_ros" "rclcpp" "geometry_msgs" "nav_msgs" "tf2_geometry_msgs" "tf2_ros")
set(robocon2027_gazebo_BUILDTOOL_DEPENDS "ament_cmake")
set(robocon2027_gazebo_BUILD_EXPORT_DEPENDS "gazebo_dev" "gazebo_ros" "rclcpp" "geometry_msgs" "nav_msgs" "tf2_geometry_msgs" "tf2_ros")
set(robocon2027_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(robocon2027_gazebo_EXEC_DEPENDS "xacro" "joint_state_publisher" "robot_state_publisher" "ament_index_python" "launch" "launch_ros" "rviz2" "gazebo_plugins" "gazebo_ros_pkgs" "ros2launch" "ros2_livox_simulation" "pointcloud_to_laserscan" "slam_toolbox" "nav2_map_server" "rclpy" "rosgraph_msgs" "sensor_msgs" "sensor_msgs_py" "gazebo_dev" "gazebo_ros" "rclcpp" "geometry_msgs" "nav_msgs" "tf2_geometry_msgs" "tf2_ros")
set(robocon2027_gazebo_TEST_DEPENDS )
set(robocon2027_gazebo_GROUP_DEPENDS )
set(robocon2027_gazebo_MEMBER_OF_GROUPS )
set(robocon2027_gazebo_DEPRECATED "")
set(robocon2027_gazebo_EXPORT_TAGS)
list(APPEND robocon2027_gazebo_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND robocon2027_gazebo_EXPORT_TAGS "<gazebo_ros gazebo_plugin_path=\"../../lib\"/>")
